name: saucectl espresso tests

on:
  pull_request:
  push:
    branches:
      - main

env:
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Saucectl RUN Sauce Cloud
        uses: saucelabs/saucectl-run-action@v1
        with:
          concurrency: 10
  cucumber-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install saucectl
        uses: saucelabs/saucectl-run-action@v1
        with:
          skip-run: true
          concurrency: 10

      - name: Espresso with Cucumber
        run: |
          cd examples/cucumber
          saucectl run
