apiVersion: v1alpha
kind: espresso
sauce:
  region: us-west-1
  # Controls how many suites are executed at the same time (sauce test env only).
  concurrency: 10
  metadata:
    tags:
      - e2e
      - release team
      - other tag
    build: Release $CI_COMMIT_SHORT_SHA
espresso:
  app: ./apps/mda-2.2.0-25.apk
  testApp: ./apps/mda-androidTest-2.2.0-25.apk
suites:
  - name: "saucy barista on Android Emulator"
    emulators:
      - name: "Android GoogleAPI Emulator"
        platformVersions:
          - "15.0"
artifacts:
  download:
    when: always
    match:
      - junit.xml
    directory: ./artifacts/

reporters:
  spotlight: # Prints an overview of failed or otherwise interesting jobs.
    enabled: true
