apiVersion: v1alpha
kind: espresso
sauce:
  region: us-west-1
  # Controls how many suites are executed at the same time (sauce test env only).
  concurrency: 10
  metadata:
    tags:
      - e2e
      - release team
      - other tag
    build: Release $CI_COMMIT_SHORT_SHA
espresso:
  app: ./apps/mda-1.0.10-12.apk
  testApp: ./apps/mda-androidTest-1.0.10-12.apk
suites:
  - name: "saucy barista - combined emulator and real devices"
    testOptions:
      class:
        - com.saucelabs.mydemoapp.android.view.activities.DashboardToCheckout
        - com.saucelabs.mydemoapp.android.view.activities.LoginTest
    emulators:
      - name: "Android GoogleAPI Emulator"
        orientation: portrait # this demo app doesn't support landscape orientation
        platformVersions:
          - "12.0"
    devices:
      - name: "Samsung.*"
        platformVersion: "8.0.0"

  - name: "saucy barista - specify device by name"
    testOptions:
      class:
        - com.saucelabs.mydemoapp.android.view.activities.LoginTest
    devices:
      - name: "Samsung.*"
        platformVersion: "8.0.0"

  - name: "saucy barista - specify device by id"
    testOptions:
      class:
        - com.saucelabs.mydemoapp.android.view.activities.LoginTest
    devices:
      - id: LG_Q6_real_us
        platformVersion: "8.0.0"

  # To remove all shared state from your device's CPU and memory after each test, use the clearPackageData + useTestOrchestrator flag.
  # Supported on real devices only.
  # https://developer.android.com/training/testing/junit-runner#using-android-test-orchestrator
  - name: "saucy barista - clear package data"
    testOptions:
      clearPackageData: true
      useTestOrchestrator: true
    devices:
      - name: "Samsung.*"

  - name: "saucy barista - package specified"
    testOptions:
      package: com.saucelabs.mydemoapp.android.view.activities
    emulators:
      - name: "Android GoogleApi Emulator"
        platformVersions:
          - "11.0"

  - name: "saucy barista - test size"
    testOptions:
      size: large
    emulators:
      - name: "Android GoogleApi Emulator"
        platformVersions:
          - "11.0"

# Controls what artifacts to fetch when the suite on Sauce Cloud has finished.
artifacts:
  download:
    when: always
    match:
      - junit.xml
    directory: ./artifacts/

reporters:
  spotlight: # Prints an overview of failed or otherwise interesting jobs.
    enabled: true
